### PR TITLE
Fix missile_b3 door bug

### LINKED ISSUE #3: Missile_b3 glitch
Missile_b3 is the official version used these days in tournaments and cups. You might wonder why b4 isn't used, that is because the last stage is even more impossible to attack than in the 3rd stage.

There is one huge glitch in missile_b3 which needs to be fixed. After the allied have conquered the first stage and have successfully destroyed the door controls, they have to build the cp and/or steal the objective and secure this to a transmitter near the axis spawn. 

After the allied have successfully secured the objective, the axis can be trapped within their spawn for 5 to 10 seconds (not sure the exact time). This is, because the back door in the axis spawn, which leads to the last stage, is blocked and only opens after some waiting. 

This can ruin the entire map for the defending team. The last stage is generally known as the stage which is the stage the be defended the easiest. Attacking teams make use (abuse) of this glitch and it happened to me more than ones that I have lost the map because of this. 

I would like to have your thoughts about this issue. It would be great to have this solved.

### PR DESCRIPTION
**Pull request by Swanidius**
Made the door work again!

Fixes #3

### CODE REVIEW

**Comment by Swanidius** [comment]
fixed stuff again

**Comment by Swanidius** [comment]
fixxxx again works now hopefully

**Comment by msh100** [comment]
The mapscript hash needs adding to `global1.config`

Also you should add a new line between on global3 and global6

```
}
+map missile_b3
```

**Comment by msh100** [comment]
Confirmed working

**Pull request merged**
